-- ══════════════════════════════════════════════════════════════════
-- INGEST_ROLE : full privilege BRONZE
-- (schémas créés par GITHUB_ROLE → grants explicites nécessaires)
-- ══════════════════════════════════════════════════════════════════

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE BRONZE TO ROLE INGEST_ROLE;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL    TABLES IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT SELECT ON ALL    TABLES IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE BRONZE TO ROLE INGEST_ROLE;

GRANT READ, WRITE ON ALL    STAGES IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT READ, WRITE ON FUTURE STAGES IN DATABASE BRONZE TO ROLE INGEST_ROLE;

GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE ON ALL    SCHEMAS IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE ON FUTURE SCHEMAS IN DATABASE BRONZE TO ROLE INGEST_ROLE;

GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE INGEST_WH TO ROLE INGEST_ROLE;

-- ══════════════════════════════════════════════════════════════════
-- TRANSFORM_ROLE : full privilege SILVER + SELECT BRONZE
-- ══════════════════════════════════════════════════════════════════

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL    TABLES IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL    TABLES IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL    VIEWS  IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;

GRANT CREATE TABLE, CREATE VIEW, CREATE TASK ON FUTURE SCHEMAS IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE TASK ON SCHEMA SILVER.TRANSFORMATION TO ROLE TRANSFORM_ROLE;

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE BRONZE TO ROLE TRANSFORM_ROLE;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE BRONZE TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL    TABLES  IN DATABASE BRONZE TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES  IN DATABASE BRONZE TO ROLE TRANSFORM_ROLE;

GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORM_ROLE;

-- ══════════════════════════════════════════════════════════════════
-- DATA_ENGINEER : lecture BRONZE + SILVER
-- ══════════════════════════════════════════════════════════════════

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL    TABLES  IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES  IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL    VIEWS   IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE VIEWS   IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT USAGE  ON ALL    STAGES  IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT USAGE  ON FUTURE STAGES  IN DATABASE BRONZE TO ROLE DATA_ENGINEER;

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL    TABLES  IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES  IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL    VIEWS   IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE VIEWS   IN DATABASE SILVER TO ROLE DATA_ENGINEER;

GRANT USAGE, OPERATE ON WAREHOUSE QUERY_WH TO ROLE DATA_ENGINEER;

-- ══════════════════════════════════════════════════════════════════
-- DATA_ANALYST : lecture seule SILVER
-- ══════════════════════════════════════════════════════════════════

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL    TABLES  IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES  IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL    VIEWS   IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS   IN DATABASE SILVER TO ROLE DATA_ANALYST;

GRANT USAGE ON WAREHOUSE QUERY_WH TO ROLE DATA_ANALYST;
