-- ══════════════════════════════════════════════════════════════════
-- INGEST_ROLE : full privilege BRONZE
-- (schémas créés par GITHUB_ROLE → grants explicites nécessaires)
-- ══════════════════════════════════════════════════════════════════

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE BRONZE TO ROLE INGEST_ROLE;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL    TABLES IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT SELECT ON ALL    TABLES IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE BRONZE TO ROLE INGEST_ROLE;

GRANT READ, WRITE ON ALL    STAGES IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT READ, WRITE ON FUTURE STAGES IN DATABASE BRONZE TO ROLE INGEST_ROLE;

GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE ON ALL    SCHEMAS IN DATABASE BRONZE TO ROLE INGEST_ROLE;
GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE ON FUTURE SCHEMAS IN DATABASE BRONZE TO ROLE INGEST_ROLE;

GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE INGEST_WH TO ROLE INGEST_ROLE;

-- ══════════════════════════════════════════════════════════════════
-- TRANSFORM_ROLE : full privilege SILVER + SELECT BRONZE
-- ══════════════════════════════════════════════════════════════════

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL    TABLES IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL    TABLES IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL    VIEWS  IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;

GRANT CREATE TABLE, CREATE VIEW, CREATE TASK, CREATE DBT PROJECT ON ALL    SCHEMAS IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE TASK, CREATE DBT PROJECT ON FUTURE SCHEMAS IN DATABASE SILVER TO ROLE TRANSFORM_ROLE;

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE BRONZE TO ROLE TRANSFORM_ROLE;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE BRONZE TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL    TABLES  IN DATABASE BRONZE TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES  IN DATABASE BRONZE TO ROLE TRANSFORM_ROLE;

GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORM_ROLE;

-- Schéma TRANSFORMATION : TRANSFORM_ROLE doit pouvoir tout faire (créer ET piloter
-- tasks/procédures — TASK_RUN_DBT_ALL, TASK_EXPORT_GOLD_TO_S3, SP_EXPORT_GOLD_TO_S3),
-- pas seulement les créer comme le permettaient les GRANT au niveau DATABASE ci-dessus.
GRANT ALL PRIVILEGES ON SCHEMA SILVER.TRANSFORMATION TO ROLE TRANSFORM_ROLE;

GRANT ALL PRIVILEGES ON ALL    TASKS IN SCHEMA SILVER.TRANSFORMATION TO ROLE TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TASKS IN SCHEMA SILVER.TRANSFORMATION TO ROLE TRANSFORM_ROLE;

GRANT ALL PRIVILEGES ON ALL    PROCEDURES IN SCHEMA SILVER.TRANSFORMATION TO ROLE TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA SILVER.TRANSFORMATION TO ROLE TRANSFORM_ROLE;

-- Privilège de COMPTE (pas schéma/DB) : sans lui, une Task créée et RESUME tourne
-- "armée" mais ses exécutions planifiées ne partent jamais sous ce rôle.
-- Nécessite que le rôle exécutant ce script (GITHUB_ROLE) ait MANAGE GRANTS, sinon
-- à lancer une fois manuellement depuis ACCOUNTADMIN.
GRANT EXECUTE TASK ON ACCOUNT TO ROLE TRANSFORM_ROLE;

-- ══════════════════════════════════════════════════════════════════
-- DATA_ENGINEER : lecture BRONZE + SILVER
-- ══════════════════════════════════════════════════════════════════

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL    TABLES  IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES  IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL    VIEWS   IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE VIEWS   IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT USAGE  ON ALL    STAGES  IN DATABASE BRONZE TO ROLE DATA_ENGINEER;
GRANT USAGE  ON FUTURE STAGES  IN DATABASE BRONZE TO ROLE DATA_ENGINEER;

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL    TABLES  IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES  IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL    VIEWS   IN DATABASE SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE VIEWS   IN DATABASE SILVER TO ROLE DATA_ENGINEER;

GRANT USAGE, OPERATE ON WAREHOUSE QUERY_WH     TO ROLE DATA_ENGINEER;
GRANT OPERATE, MONITOR ON WAREHOUSE TRANSFORM_WH TO ROLE DATA_ENGINEER;

-- ══════════════════════════════════════════════════════════════════
-- DATA_ANALYST : lecture seule SILVER
-- ══════════════════════════════════════════════════════════════════

GRANT USAGE  ON ALL    SCHEMAS IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL    TABLES  IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES  IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL    VIEWS   IN DATABASE SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS   IN DATABASE SILVER TO ROLE DATA_ANALYST;

GRANT USAGE ON WAREHOUSE QUERY_WH TO ROLE DATA_ANALYST;
