-- Grants schéma/table sur BRONZE pour TRANSFORM_ROLE et DATA_ENGINEER
-- (les database-level grants sont gérés par Terraform)

USE DATABASE BRONZE;
USE ROLE INGEST_ROLE;

-- TRANSFORM_ROLE : lit BRONZE pour alimenter SILVER via dbt
GRANT USAGE  ON SCHEMA BRONZE.AIR_QUALITY TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON TABLE  BRONZE.AIR_QUALITY.RAW_AIR_QUALITY  TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON TABLE  BRONZE.AIR_QUALITY.RAW_COORDONNEES  TO ROLE TRANSFORM_ROLE;

-- DATA_ENGINEER : lecture complète BRONZE pour exploration console
GRANT USAGE  ON SCHEMA BRONZE.AIR_QUALITY TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA BRONZE.AIR_QUALITY TO ROLE DATA_ENGINEER;
