-- Création des schémas SILVER
-- Le projet dbt vit dans TRANSFORMATION et écrit dans AIR_QUALITY, MOBILITE, SMARTCITY

USE DATABASE SILVER;
USE ROLE TRANSFORM_ROLE;

CREATE SCHEMA IF NOT EXISTS TRANSFORMATION;  -- dbt project home (déployé via Snow CLI)


-- Lecture DATA_ENGINEER et DATA_ANALYST sur tous les schémas SILVER
USE ROLE TRANSFORM_ROLE;

GRANT USAGE ON SCHEMA SILVER.TRANSFORMATION TO ROLE DATA_ENGINEER;


GRANT SELECT ON ALL TABLES IN SCHEMA SILVER.AIR_QUALITY  TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER.MOBILITE     TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER.SMARTCITY    TO ROLE DATA_ENGINEER;

GRANT USAGE  ON SCHEMA SILVER.AIR_QUALITY   TO ROLE DATA_ANALYST;
GRANT USAGE  ON SCHEMA SILVER.MOBILITE      TO ROLE DATA_ANALYST;
GRANT USAGE  ON SCHEMA SILVER.SMARTCITY     TO ROLE DATA_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA SILVER.AIR_QUALITY  TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER.MOBILITE     TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER.SMARTCITY    TO ROLE DATA_ANALYST;
