USE DATABASE SILVER;
USE SCHEMA TRANSFORMATION;
USE ROLE TRANSFORM_ROLE;

-- Task quotidienne : build complet du projet dbt à 08h00 (après le dépôt S3 J-1)
-- Le projet est déployé dans SILVER.TRANSFORMATION via Snow CLI
-- Les modèles s'écrivent dans SILVER.AIR_QUALITY, SILVER.MOBILITE, SILVER.SMARTCITY

CREATE OR REPLACE TASK TASK_RUN_DBT_ALL
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE  = 'USING CRON 0 8 * * * Europe/Paris'
AS
  EXECUTE DBT PROJECT SILVER.TRANSFORMATION ARGS 'build';

ALTER TASK TASK_RUN_DBT_ALL RESUME;
