USE DATABASE BRONZE;
USE ROLE INGEST_ROLE;

-- TRANSFORM_ROLE lit BRONZE.MOBILITE pour alimenter SILVER via dbt
GRANT USAGE  ON SCHEMA BRONZE.MOBILITE TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA BRONZE.MOBILITE TO ROLE TRANSFORM_ROLE;

-- DATA_ENGINEER exploration console
GRANT USAGE  ON SCHEMA BRONZE.MOBILITE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA BRONZE.MOBILITE TO ROLE DATA_ENGINEER;
