-- Task déclenchée automatiquement après la fin de TASK_RUN_DBT_ALL
-- Pas de SCHEDULE propre : elle hérite du déclencheur parent (dbt à 08:00)
USE DATABASE SILVER;
USE SCHEMA TRANSFORMATION;
USE ROLE TRANSFORM_ROLE;

CREATE OR REPLACE TASK TASK_EXPORT_TO_GOLD
  WAREHOUSE = TRANSFORM_WH
  AFTER     TASK_RUN_DBT_ALL
AS
  CALL PROC_EXPORT_SILVER_TO_GOLD();

ALTER TASK TASK_EXPORT_TO_GOLD RESUME;
