USE DATABASE SILVER;
USE SCHEMA TRANSFORMATION;
CREATE OR REPLACE NOTIFICATION INTEGRATION SNS_NOVASIGHT_ALERTS
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AWS_SNS
  ENABLED = TRUE
  AWS_SNS_TOPIC_ARN = 'arn:aws:sns:eu-west-3:${AWS_ACCOUNT_ID}:novasight-alerts'  
  AWS_SNS_ROLE_ARN  = 'arn:aws:iam::${AWS_ACCOUNT_ID}:role/projet-efrei-role';  


-- Rattacher la notification aux Tasks existantes
ALTER TASK SILVER.TRANSFORMATION.TASK_RUN_DBT_ALL
  SET ERROR_INTEGRATION = SNS_NOVASIGHT_ALERTS;

ALTER TASK SILVER.TRANSFORMATION.TASK_EXPORT_GOLD_TO_S3
  SET ERROR_INTEGRATION = SNS_NOVASIGHT_ALERTS;