USE DATABASE SILVER;
USE SCHEMA TRANSFORMATION;

-- Création de l'intégration avec un rôle privilégié
USE ROLE GITHUB_ROLE;

CREATE OR REPLACE NOTIFICATION INTEGRATION SNS_NOVASIGHT_ALERTS
  TYPE = QUEUE
  DIRECTION = OUTBOUND
  NOTIFICATION_PROVIDER = AWS_SNS
  ENABLED = TRUE
  AWS_SNS_TOPIC_ARN = 'arn:aws:sns:eu-west-3:${AWS_ACCOUNT_ID}:novasight-alerts'
  AWS_SNS_ROLE_ARN  = 'arn:aws:iam::${AWS_ACCOUNT_ID}:role/projet-efrei-role';

-- Accorder USAGE au rôle owner des tasks
GRANT USAGE ON INTEGRATION SNS_NOVASIGHT_ALERTS TO ROLE TRANSFORM_ROLE;

-- Basculer sur TRANSFORM_ROLE pour modifier les tasks
USE ROLE TRANSFORM_ROLE;

ALTER TASK SILVER.TRANSFORMATION.TASK_RUN_DBT_ALL
  SET ERROR_INTEGRATION = SNS_NOVASIGHT_ALERTS;

USE ROLE GITHUB_ROLE;